# -*- coding: utf-8 -*-
"""Commodity_Prices_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyEr8BV_VPsU1FG278XRcHxWBhxXlLY0
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

df = pd.read_csv(r'/content/commodity_prices (1).csv')
df

df.head()

df.shape #how many rows and columns

df.duplicated().sum()

df.describe().round()



# Convert date column to datetime format
df['date'] = pd.to_datetime(df['date'])

# Drop the unnecessary column (Unnamed: 0)
df.drop(columns=['Unnamed: 0'], inplace=True)

# Exploratory Data Analysis
print("Dataset Info:")
print(df.info())
print("\nBasic Statistics:")
print(df.describe())

# Answer the case study questions
# 1. What is the maximum price of Robusta coffee?
max_robusta_price = df['coffee_robustas'].max()
print(f"Maximum price of Robusta coffee: {max_robusta_price}")

# 2. What is the 75th percentile of sugar prices in the EU?
p75_sugar_eu = np.percentile(df['sugar_eu'], 75)
print(f"75th percentile of sugar prices in the EU: {p75_sugar_eu}")

# 3. What is the skewness of the price distribution for Arabica coffee?
skew_arabica = df['coffee_arabica'].skew()
print(f"Skewness of Arabica coffee prices: {skew_arabica}")

# 4. Is the distribution of sugar prices in the US significantly different from normal?
mean_sugar_us = df['sugar_us'].mean()
std_sugar_us = df['sugar_us'].std()
z_scores = (df['sugar_us'] - mean_sugar_us) / std_sugar_us
is_significantly_different = (z_scores.abs() > 3).any()
if is_significantly_different:
    print("Sugar prices in the US are significantly different from a normal distribution.")
else:
    print("Sugar prices in the US are not significantly different from a normal distribution.")

# 5. How many times does the price of Dubai oil exceed Brent oil by $10?
thresh_exceed = (df['oil_dubai'] - df['oil_brent']) > 10
count_exceed = thresh_exceed.sum()
print(f"Number of times Dubai oil exceeds Brent oil by $10: {count_exceed}")

# Additional Insights
# 6. Which commodity experienced the highest price fluctuations during the observed period?
fluctuations = df.std().drop('date')
highest_fluctuation = fluctuations.idxmax()
print(f"Commodity with highest price fluctuations: {highest_fluctuation}")

# 7. Correlation analysis between global sugar prices and regional sugar prices
correlation_global_eu = df['sugar_world'].corr(df['sugar_eu'])
correlation_global_us = df['sugar_world'].corr(df['sugar_us'])
print(f"Correlation between global and EU sugar prices: {correlation_global_eu}")
print(f"Correlation between global and US sugar prices: {correlation_global_us}")

# Visualization
# Overall trends for each commodity
plt.figure(figsize=(12, 8))
for column in df.columns[1:]:
    if column != 'date':
        plt.plot(df['date'], df[column], label=column)
plt.title('Overall Price Trends')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.show()

# Visualization for Additional Insights
# 7.1 Boxplot for price fluctuations of all commodities
plt.figure(figsize=(12, 6))
sns.boxplot(data=df.drop(columns=['date']))
plt.title('Price Fluctuations Across Commodities')
plt.xlabel('Commodities')
plt.ylabel('Price')
plt.xticks(rotation=45)
plt.show()

# 7.2 Heatmap for correlation between all commodities
plt.figure(figsize=(10, 8))
corr_matrix = df.drop(columns=['date']).corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Commodities')
plt.show()

# 7.3 Yearly average prices for each commodity
df['year'] = df['date'].dt.year
yearly_avg = df.groupby('year').mean()
plt.figure(figsize=(12, 8))
for column in yearly_avg.columns:
    plt.plot(yearly_avg.index, yearly_avg[column], label=column)
plt.title('Yearly Average Prices')
plt.xlabel('Year')
plt.ylabel('Average Price')
plt.legend()
plt.show()

# Save this script for running in Google Colab

# Convert date column to datetime format
df['date'] = pd.to_datetime(df['date'])

# Drop the unnecessary column (Unnamed: 0)
# df.drop(columns=['Unnamed: 0'], inplace=True)

# Exploratory Data Analysis
print("Dataset Info:")
print(df.info())
print("\nBasic Statistics:")
print(df.describe())

# 1. Line Plot: Overall price trends
plt.figure(figsize=(12, 8))
for column in df.columns[1:]:
    if column != 'date':
        plt.plot(df['date'], df[column], label=column)
plt.title('Overall Price Trends Over Time')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid()
plt.show()

# 2. Histogram: Price distribution of Arabica coffee
plt.figure(figsize=(8, 6))
plt.hist(df['coffee_arabica'], bins=20, color='skyblue', edgecolor='black')
plt.title('Price Distribution of Arabica Coffee')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.grid()
plt.show()

# 3. Scatter Plot: Correlation between EU and US sugar prices
plt.figure(figsize=(8, 6))
sns.scatterplot(x=df['sugar_eu'], y=df['sugar_us'], color='red')
plt.title('Correlation between EU and US Sugar Prices')
plt.xlabel('EU Sugar Prices ($/kg)')
plt.ylabel('US Sugar Prices ($/kg)')
plt.grid()
plt.show()

# 4. Box Plot: Fluctuations across all commodities
plt.figure(figsize=(12, 6))
sns.boxplot(data=df.drop(columns=['date']))
plt.title('Price Fluctuations Across Commodities')
plt.xlabel('Commodities')
plt.ylabel('Price')
plt.xticks(rotation=45)
plt.grid()
plt.show()

# 5. Bar Plot: Quarterly average of Brent oil prices for the last 5 years
last_five_years = df[df['date'] >= pd.Timestamp('2017-01-01')]
last_five_years['quarter'] = last_five_years['date'].dt.to_period('Q')
quarterly_avg = last_five_years.groupby('quarter')['oil_brent'].mean()
plt.figure(figsize=(12, 6))
quarterly_avg.plot(kind='bar', color='teal')
plt.title('Quarterly Average of Brent Oil Prices (Last 5 Years)')
plt.xlabel('Quarter')
plt.ylabel('Average Price ($/bbl)')
plt.grid()
plt.show()

# Insights
# Highest and lowest fluctuations
fluctuations = df.std().drop('date')
highest_fluctuation = fluctuations.idxmax()
lowest_fluctuation = fluctuations.idxmin()
print(f"Commodity with highest price fluctuations: {highest_fluctuation}")
print(f"Commodity with lowest price fluctuations: {lowest_fluctuation}")

# Correlation Analysis
correlation_matrix = df.corr()
global_correlation = correlation_matrix['sugar_world'].sort_values(ascending=False)
print("\nCorrelation of global sugar prices with other commodities:")
print(global_correlation)

# Save this script for running in Google Colab

# 7. Quarterly trends for Robusta coffee in the last 5 years
last_five_years['quarter'] = last_five_years['date'].dt.to_period('Q')
robusta_quarterly_avg = last_five_years.groupby('quarter')['coffee_robustas'].mean()
plt.figure(figsize=(12, 6))
robusta_quarterly_avg.plot(kind='bar', color='purple')
plt.title('Quarterly Average of Robusta Coffee Prices (Last 5 Years)')
plt.xlabel('Quarter')
plt.ylabel('Average Price ($/kg)')
plt.grid()
plt.show()